In [1]:
import numpy as np
import pandas as pd

In [10]:
#Exercici 1 Resumen estadístico de array

def resumen_estadistico(arr):
    if(arr.ndim == 1):
        df0 = pd.DataFrame(arr)
        print(df0.describe())
        return df0
    else:
        print("La array no tiene el formato correcto")

In [11]:
a = np.arange(4)
b = np.eye(2)

In [12]:
resumen_estadistico(a)

              0
count  4.000000
mean   1.500000
std    1.290994
min    0.000000
25%    0.750000
50%    1.500000
75%    2.250000
max    3.000000


0
0  0
1  1
2  2
3  3

In [13]:
resumen_estadistico(b)

La array no tiene el formato correcto


In [14]:
#Exercici 2 Función para generar cuadrado NxN

In [15]:
def create_square(i):
    return np.random.randint(101, size=(i,i))

In [16]:
create_square(2)

array([[13, 69],
       [53, 20]])

In [17]:
create_square(5)

array([[62, 36, 85, 67, 34],
       [36, 73, 68, 25, 45],
       [88, 83, 35, 77, 10],
       [ 9, 20, 34, 74,  7],
       [40, 16, 57, 37, 95]])

In [18]:
#Exercici 3 Calcular los totales
def sum_lines(arr):
    if(arr.ndim == 2):
        df1 = pd.DataFrame(arr)
        df2 = pd.DataFrame(df1.sum(axis=1))
        for i in df1:
            print("La suma de la columna "+str(i+1)+" es: "+str(df1[i].sum()))
        print(" ")
        for x in range(len(df2[0])):
            print("La suma de la fila "+str(x+1)+" es: "+str(df2[0][x]))
    else:
        print("La array no es de 2 dimensiones")

In [19]:
sum_lines(b)

La suma de la columna 1 es: 1.0
La suma de la columna 2 es: 1.0
 
La suma de la fila 1 es: 1.0
La suma de la fila 2 es: 1.0


In [20]:
sum_lines(a)

La array no es de 2 dimensiones


In [21]:
a

array([0, 1, 2, 3])

In [29]:
#Exercici 4
z = np.random.randint(100, size=5)
x = np.random.randint(100, size=5)
print(np.corrcoef(x,z))

[[1.        0.1281913]
 [0.1281913 1.       ]]
